var uri = "http://mjailton.com.br/capitulo 2 - funções"
var uriCodificada = encodeURI(uri)
var uriCodificadaComponente = encodeURIComponent(uri)
var uriDecodificada = decodeURI(uri)
var uriDecodificadaComponente = decodeURIComponent(uri)

console.log(uri)
console.log(uriCodificada)
console.log(uriDecodificada)
console.log(uriCodificadaComponente)
console.log(uriDecodificadaComponente)

console.log("\nisFinite()")
console.log(isFinite(10))
console.log(isFinite(10/0))
console.log(isFinite("10"))
console.log(isFinite("10auhau"))
console.log(isFinite("auhau10"))

console.log("\nisNaN()")
console.log(isNaN(10))
console.log(isNaN(10/0))
console.log(isNaN("10"))
console.log(isNaN("10auhau"))
console.log(isNaN("auhau10"))

console.log("\nNumber()")
console.log(Number(10))
console.log(Number(10/0))
console.log(Number("10"))
console.log(Number("10auhau"))
console.log(Number("auhau10"))

console.log("\nparseFloat()")
console.log(parseFloat(10))
console.log(parseFloat(10/0))
console.log(parseFloat("10"))
console.log(parseFloat("10.2auhau"))
console.log(parseFloat("auhau10"))

console.log("\nparseInt()")
console.log(parseInt(10))
console.log(parseInt(10/0))
console.log(parseInt("10"))
console.log(parseInt("10.2auhau"))
console.log(parseInt("auhau10"))

console.log("\nString()")
console.log(String(10))
console.log(String(10/0))
console.log(String("10"))
console.log(String("10.2auhau"))
console.log(String("auhau10"))

